version: '3.9'
services:
  mysql:
      image: 'mysql/mysql-server:8.0'
      ports:
          - '${FORWARD_DB_PORT:-3306}:3306'
      environment:
          MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
          MYSQL_ROOT_HOST: "%"
          MYSQL_DATABASE: '${DB_DATABASE}'
          MYSQL_USER: '${DB_USERNAME}'
          MYSQL_PASSWORD: '${DB_PASSWORD}'
          MYSQL_ALLOW_EMPTY_PASSWORD: 1
      volumes:
          - 'home-mysql:/var/lib/mysql'
      networks:
          - home
      healthcheck:
          test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
          retries: 3
          timeout: 5s
  phpmyadmin:
    image: 'phpmyadmin'
    environment:
      - PMA_HOST=mysql
      - UPLOAD_LIMIT=2G
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    ports:
      - '${FORWARD_PHPMYADMIN_PORT:-8080}:80'
    volumes:
      - 'home-phpmyadmin:/session'
    networks:
      - home
    depends_on:
      - mysql
  redis:
    image: 'redis:alpine'
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - '${FORWARD_REDIS_PORT:-6379}:6379'
    volumes:
      - 'home-redis:/data'
    networks:
      - home
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      retries: 3
      timeout: 5s
  redis-stack:
    image: 'redis/redis-stack:latest'
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - '${FORWARD_REDIS_PORT:-6379}:6379'
    volumes:
      - 'home-redis-stack:/data'
    networks:
      - home
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      retries: 3
      timeout: 5s
  pgsql:
    image: 'postgres:14'
    ports:
        - '${FORWARD_DB_PORT:-5432}:5432'
    environment:
        PGPASSWORD: '${DB_PASSWORD:-secret}'
        POSTGRES_DB: '${DB_DATABASE}'
        POSTGRES_USER: '${DB_USERNAME}'
        POSTGRES_PASSWORD: '${DB_PASSWORD:-secret}'
    volumes:
        - 'home-pgsql:/var/lib/postgresql/data'
    networks:
        - home
    healthcheck:
        test: ["CMD", "pg_isready", "-q", "-d", "${DB_DATABASE}", "-U", "${DB_USERNAME}"]
        retries: 3
        timeout: 5s
networks:
  home:
    driver: bridge
volumes:
  home-mysql:
    driver: local
  home-phpmyadmin:
    driver: local
  home-redis:
    driver: local
  home-redis-stack:
    driver: local
  home-pgsql:
    driver: local
